db:
  url: "jdbc:postgresql://localhost:5432/temperature_alerts"
  driver: "org.postgresql.Driver"
  user: "postgres"
  
sensorAPI:
  clientId: "d133dea9ee3949b393ac28a1c58f2737"
  host: "room-temperature-api-u7lwhs.5sc6y6-1.usa-e2.cloudhub.io"
  port: "443"
  protocol: "HTTPS"
  basePath: "/api"
  
http:
  port: "8082"